// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'activeFilter': string;
  'clearLookupButton': string;
  'filterButtons': string;
  'helpText': string;
  'message': string;
  'noResults': string;
  'providerSelect': string;
  'providerSelectContainer': string;
  'providerSelectIcon': string;
  'searchContainer': string;
  'searchIconContainer': string;
  'searchInput': string;
  'searchResults': string;
}
export const cssExports: CssExports;
export default cssExports;
