// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'duration': string;
  'indexerFlags': string;
  'monitored': string;
  'narrator': string;
  'pageCount': string;
  'position': string;
  'rating': string;
  'releaseDate': string;
  'select': string;
  'status': string;
  'table': string;
}
export const cssExports: CssExports;
export default cssExports;
