// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'container': string;
  'option': string;
  'slider': string;
  'sliderAll': string;
}
export const cssExports: CssExports;
export default cssExports;
