#!/bin/bash

source _common.sh

ynh_script_progression "Stopping ChaptarrNG..."
ynh_systemctl --service="$app" --action="stop"

ynh_script_progression "Removing the YunoHost service and reverse proxy..."
if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi
ynh_config_remove_systemd
ynh_config_remove_nginx

ynh_script_progression "ChaptarrNG removal completed"
